logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8080


openai:
  api:
    key: ${OPEN_API_KEY}
    url: ${OPEN_API_URL}

---

spring.config.activate.on-profile: local

spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test;MODE=MYSQL
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
spring.config.activate.on-profile: live

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${STORAGE_DATABASE_CORE_DB_URL}
      username: ${STORAGE_DATABASE_CORE_DB_USERNAME}
      password: ${STORAGE_DATABASE_CORE_DB_PASSWORD}
      maximum-pool-size: 25
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
