logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

openai:
  api:
    key: ${OPEN_API_KEY}
    url: ${OPEN_API_URL}

azure:
  storage:
    account-name: ${BLOB_ACCOUNT_NAME}
    account-key: ${BLOB_ACCOUNT_KEY}
    endpoint: ${BLOB_ENDPOINT}

---

spring.config.activate.on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

storage:
  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:test/hexagonal;NON_KEYWORDS=USER
      username: sa
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: live

storage:
  datasource:
    core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://${STORAGE_DATABASE_CORE_DB_URL}
      username: ${STORAGE_DATABASE_CORE_DB_USERNAME}
      password: ${STORAGE_DATABASE_CORE_DB_PASSWORD}
      maximum-pool-size: 25
      connection-timeout: 1100
      keepalive-time: 30000
      validation-timeout: 1000
      max-lifetime: 600000
      pool-name: core-db-pool
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

